version: 2
project_name: apm

before:
  hooks:
    - go mod tidy

builds:
  - id: apm
    binary: apm
    main: ./main.go
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
    env:
      - CGO_ENABLED=0

archives:
  - id: default
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    files:
      - LICENSE
      - README.md
    format_overrides:
      - goos: windows
        format: zip

nfpm:
  - id: apm
    formats:
      - deb
    package_name: apm
    vendor: "APM"
    maintainer: "Aarav Maloo <aaravmaloo06@gmail.com>"
    homepage: "https://aaravmaloo.github.io/apm/"
    description: "Advanced Package Manager."
    license: MIT

checksum:
  name_template: "checksums.txt"

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'

release:
  github:
    owner: "aaravmaloo"
    name: "apm"
    draft: false
    prerelease: false